### ISSUE TITLE
"Show vertical scrollbar" should be activated by default

### ISSUE THREAD

**Issue by paintdog** [thegli/yfquotes-cinnamon-desklet#6]
The new feature to enable or disable the vertical scroll bar came with version 0.11.0 on March 15, 2024 and was disabled by default. This causes the stock list to flow across the desklet until the user activates the vertical scroll bar. I think it would be useful for most users if vertical scrollbar was enabled by default.

**Comment by thegli** [comment]
I decided for a change of the default setting, because the scrollbar always takes up the space even if the content is fully shown, and there is nothing to scroll. I would assume that most users tailor the size of the desklet that way, so I wanted to give them the wasted space back :smiley:
I'd say this is a personal preference, and the default option - enabled or disabled - is either "just right" or "need to change that" for you.

**Comment by paintdog** [comment]
I understand your motivation. I'll describe my impression: After the update it just looked broken to me. Too many users might have had this impression, which would be unfortunate given the usefulness of your desklet.

**Comment by thegli** [comment]
The behavior change was released 2 months ago, and this was the only feedback I got so far. Therefore I close this issue.
@paintdog: Thanks again for your input
